### ISSUE TITLE
UI Cleanup: Ensure Clean UI Across the App

### ISSUE THREAD

**Issue by SeanKudrna** [HellowLab/DblFeature#41]
Ensure the UI is clean and consistent across the app, with a focus on minimizing features to limit scope for the first release.

**Comment by mango23322** [comment]
I made some changes to how the search screen displays 

- the search text only changes when a user changes it. Before it would change to the movie title when you click on a movie. 

- I also made it so the movie just pops up as a modal, and you can still see the search results in the background 

- also changed from flip card to "MovieCardOne" for the movie card modal

**Comment by SeanKudrna** [comment]
- [x] Dynamic expanding bio footer on movie cards. [Sean]
- [x] Add movie details to My Movies screen list items. [Mango]
- [x] Dark/Light mode styling on MovieCardOne component. [Mango]
- [x] Use device theme by default (Dark/Light). [Mango]
- [x] Remove New Matches screen icon from tab navigator. 
- [x] Make header text on the blue white always.
- [x] Back button from home screen results in null screen (figure out how to use router.replace rather than router.push from login/index)

**Comment by mango23322** [comment]
for the "add movie details to My Movies screen", we are currently iterating over the DjangoMovie list for liked / disliked movies. In order to display tmdb movie infor we would need to do a bit of refactoring. I'd like to save that for v1.1. For now I cleaned it up by adding My Rating and Swipe Date to the component

![Image](https://github.com/user-attachments/assets/75ebf11e-cb26-4a3c-8f7e-ba79b0b80750)
